include("QuestDiary/game/R/XuanYou.lua")                   --玄幽
include("QuestDiary/game/R/YuanSuZhiXi.lua")                   --元素之心
include("QuestDiary/game/R/ShiPoShenXiang.lua")                   --湿婆神像
include("QuestDiary/game/R/HeiChiBaoZang.lua")  --黑齿宝藏
include("QuestDiary/game/R/AnYuLieXi.lua")  --暗域裂缝
include("QuestDiary/game/R/FengYinJiTan.lua")     --封印祭坛
include("QuestDiary/game/R/XinYueBaoZhu.lua")     --新月宝珠
include("QuestDiary/game/R/BeiFengYinDeFengYinGuanGuo.lua")     --被封印的封印棺椁
include("QuestDiary/game/R/YingLingJiTan.lua")     --英灵祭坛
include("QuestDiary/game/R/JianLingChuanShuo.lua")     --剑灵传说
include("QuestDiary/game/R/GuLongDeChuanCheng.lua")     --古龙的传承
include("QuestDiary/game/R/MieShiLingYu.lua")     --灭世领域

include("QuestDiary/game/R/YunLie.lua")     --云烈
include("QuestDiary/game/R/ShenLongShiWei.lua")     --神龙侍卫
include("QuestDiary/game/R/ManHuangXueMai.lua")     --蛮荒血脉
include("QuestDiary/game/R/HuangShaZhiLing.lua")     --黄沙之灵
include("QuestDiary/game/R/LeiMingZhiLi.lua")     --雷鸣之力
include("QuestDiary/game/R/LingHunLaoLong.lua")     --灵魂牢笼
include("QuestDiary/game/R/ShengSiJingJie.lua")     --生死境界
include("QuestDiary/game/R/YiJiangGongChengWanGuKu.lua")     --一将功成万古枯
include("QuestDiary/game/R/GuiLingYiShi.lua")     --归灵仪式
include("QuestDiary/game/R/ZuLongMiBao.lua")     --祖龙秘宝
include("QuestDiary/game/R/QianXianXianFeng.lua")     --前线先锋
include("QuestDiary/game/R/BeiMingShaoTa.lua")     --悲鸣哨塔
include("QuestDiary/game/R/PingPanJiangLing.lua")     --平叛将领
include("QuestDiary/game/R/YongHengHuiJi.lua")     --永恒徽记
include("QuestDiary/game/R/ZuLongZhiDi.lua")     --祖龙之地
include("QuestDiary/game/R/YouMingGuiShi.lua")     --幽冥鬼使
include("QuestDiary/game/R/LianHunLu.lua")     --炼魂炉
include("QuestDiary/game/R/YinYangBaGuaPan.lua")     --阴阳八卦盘
include("QuestDiary/game/R/FengDouGuiQi.lua")     --酆都鬼器
include("QuestDiary/game/R/GuiYuLingQi.lua")     --鬼域灵器
include("QuestDiary/game/R/YanWangDaDian.lua")     --阎王大殿
include("QuestDiary/game/R/CuiPanGuan.lua")     --崔判官
include("QuestDiary/game/R/SheChaoJinDi.lua")     --蛇巢禁地
include("QuestDiary/game/R/WangLingZhiShu.lua")     --亡灵之书
include("QuestDiary/game/R/HeiShuiMiJi.lua")     --黑水秘技
include("QuestDiary/game/R/MoYanLianYu.lua")     --魔焰炼狱
include("QuestDiary/game/R/LiuDaoLunHuiPan.lua")     --六道轮回盘
include("QuestDiary/game/R/HongHuangZhiMen.lua")     --洪荒之门
include("QuestDiary/game/R/WuXingLingTi.lua")     --五行灵体
include("QuestDiary/game/R/TianJieZhiLu.lua")     --天劫之路
include("QuestDiary/game/R/DanChen.lua")     --丹尘
include("QuestDiary/game/R/TanYuBuZhi.lua")     --贪欲不止
include("QuestDiary/game/R/FoFaWuBian.lua")     --佛法无边
include("QuestDiary/game/R/FengXingZhe.lua")     --风行者
include("QuestDiary/game/R/MieShiLaoLong.lua")     --灭世牢笼
include("QuestDiary/game/R/LongQiMieShiHaiGu.lua")     --龙器灭世骸骨
include("QuestDiary/game/R/HanShuangWangZuo.lua")     --寒霜王座
include("QuestDiary/game/R/HongHuangZhiLi.lua")     --洪荒之力
include("QuestDiary/game/R/GeBuLinDeRuoDian.lua")     --哥布林的弱点
include("QuestDiary/game/R/JieJiuShaoNv.lua")     --解救少女
include("QuestDiary/game/R/YiYeYiPuTi.lua")     --一叶一菩提
include("QuestDiary/game/R/YueGuangYuHui.lua")     --月光余晖
include("QuestDiary/game/R/ChaoJiJuQing.lua")     --超级剧情
include("QuestDiary/game/R/ZhuXianRenWu.lua")     --主线任务
include("QuestDiary/game/R/TongGuanWenDie.lua")     --通关文牒